### ISSUE TITLE
Searching for keyword with artist name causes KeyError: 'name'

### ISSUE THREAD

**Issue by meets7** [arcward/ticketpy#2]
I tried doing this:

`tm_client.events.find(keyword="hans")`

But got the following exception (with trace)

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/query.py", line 267, in find
    client_visibility=client_visibility, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/query.py", line 86, in _get
    return self.__get(**params)
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/query.py", line 53, in __get
    response = self.api_client.search(self.method, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/client.py", line 91, in search
    return PagedResponse(self, self._handle_response(resp))
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/client.py", line 206, in __init__
    self.page = Page.from_json(response)
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/model.py", line 61, in from_json
    pg += [obj_type.from_json(obj) for obj in v]
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/model.py", line 61, in <listcomp>
    pg += [obj_type.from_json(obj) for obj in v]
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/model.py", line 182, in from_json
    venues.append(Venue.from_json(v))
  File "/usr/local/lib/python3.5/dist-packages/ticketpy/model.py", line 293, in from_json
    v.name = json_venue['name']
KeyError: 'name'
`

Running the search on http://developer.ticketmaster.com/api-explorer/ returns results. Specifically, it results in the following URL:

https://app.ticketmaster.com/discovery/v2/events.json?apikey=*********************&keyword=hans

Attached response file: [responsedump.txt](https://github.com/arcward/ticketpy/files/1033911/responsedump.txt)

**Comment by arcward** [comment]
It looks like one of the event entries would be missing a name, but I reformatted your response dump to JSON to see if I could figure out which one but it parsed it correctly (I searched for 'hans' too but figured the event might have already passed). Strange. Was it happening consistently / does it still happen with any other searches ?

**Comment by tchandler** [comment]
Edit: I commented here having used the version of ticketpy that I got when I used `pip` to install it. Loading the package from this repo instead fixes the issue.

I came across the same error as well, it appears that some venues are missing certain data points. I've seen errors for both a missing name and a missing `line1` under address.

This is a query generated by ticketpy for Coldplay, their next show appears to be in Hamburg, and the venue is light on details: 
` /discovery/v2/events.json?sort=date%2Casc&apikey=njqMAN6uVaOdGzasv7pVNG4Uot3oBDBY&size=1&attractionId=K8vZ9171izV`
```json
{
    "type": "venue",
    "id": "Z598xZC2Za7d7",
    "test": false,
    "url": "http://www.ticketmaster.de/venue/barclaycard-arena-hamburg-tickets/hamozweiwo/716",
    "locale": "en-us",
    "postalCode": "22525",
    "timezone": "Europe/Berlin",
    "city": {
        "name": "Hamburg"
    },
    "country": {
        "name": "Germany",
        "countryCode": "DE"
    },
    "address": {
        "line1": "Sylvesterallee 10"
    },
    "location": {
        "longitude": "9.899",
        "latitude": "53.58894"
    },
    "upcomingEvents": {
        "_total": 31,
        "mfx-de": 31
    },
    "_links": {
        "self": {
            "href": "/discovery/v2/venues/Z598xZC2Za7d7?locale=en-us"
        }
    }
}
```

In fact, if you try to query that venue's id `https://app.ticketmaster.com/discovery/v2/venues.json?apikey=njqMAN6uVaOdGzasv7pVNG4Uot3oBDBY&id=Z598xZC2Za7d7` it doesn't find anything.

**Comment by arcward** [comment]
a bit late, but i finally got some time to come back around and realized querying objects by ID was skipping the response handler, so a 404 on an ID that doesn't return a venue was being deserialized into the Venue object with missing data points instead of throwing an ApiException. i fixed that as well, and pushed a new release to pypi!
