### ISSUE TITLE
Date Filters aren't working anymore

### ISSUE THREAD

**Issue by payne19** [arcward/ticketpy#7]
Thank you very much for this code. but start_date_time and end_date_time filters have no effect on the code anymore whenever I run with the dates filter the data isn't getting gathered anymore. can you please help me with this?
![Screenshot 2022-10-31 181147](https://user-images.githubusercontent.com/54582569/199010652-1449c34e-bd99-449f-ab75-05a738218e12.png)
 Thank you.

**Comment by arcward** [comment]
I'm inclined to think they limit the results for past dates - if I search back from a few days ago to a few years, there are only 40 results
